# Worksheet 12

Name:  Tianyi Bao
UID: U89641075

### Topics

- Naive Bayes
- Model Evaluation

### Naive Bayes

| Attribute A | Attribute B | Attribute C | Class |
|-------------|-------------|-------------|-------|
| Yes         | Single      | High        | No    |
| No          | Married     | Mid         | No    |
| No          | Single      | Low         | No    |
| Yes         | Married     | High        | No    |
| No          | Divorced    | Mid         | Yes   |
| No          | Married     | Low         | No    |
| Yes         | Divorced    | High        | No    |
| No          | Single      | Mid         | Yes   |
| No          | Married     | Low         | No    |
| No          | Single      | Mid         | Yes   |

a) Compute the following probabilities:

- P(Attribute A = Yes | Class = No)
- P(Attribute B = Divorced | Class = Yes)
- P(Attribute C = High | Class = No)
- P(Attribute C = Mid | Class = Yes)

- P(Attribute A = Yes | Class = No) = 3/7
- P(Attribute B = Divorced | Class = Yes) = 1/3
- P(Attribute C = High | Class = No) = 3/7
- P(Attribute C = Mid | Class = Yes) = 1

b) Classify the following unseen records:

- (Yes, Married, Mid)
- (No, Divorced, High)
- (No, Single, High)
- (No, Divorced, Low)


- (Yes, Married, Mid) 

   P(X|Yes) = P(Yes|Yes)*P(Married|Yes)*P(Mid|Yes) = 0

   P(X|No) = P(Yes|No)*P(Married|No)*P(Mid|No) = 3/7 * 4/7 * 1/7 > P(X|Yes)

   predict class: No


- (No, Divorced, High)

   P(X|Yes) = P(No|Yes)*P(Divorced|Yes)*P(High|Yes) = 1 * 1/3 * 0 = 0

   P(X|No) = P(No|No)*P(Divorced|No)*P(High|No) = 4/7 * 1/7 * 3/7 > P(X|Yes)

   predict class: No


- (No, Single, High)

   P(X|Yes) = P(No|Yes)*P(Single|Yes)*P(High|Yes) = 1 * 2/3 * 0 = 0

   P(X|No) = P(No|No)*P(Single|No)*P(High|No) = 4/7 * 2/7 * 3/7 > P(X|Yes)

   predict class: No


- (No, Divorced, Low)

   P(X|Yes) = P(No|Yes)*P(Divorced|Yes)*P(Low|Yes) = 1 * 1/3 * 0 = 0

   P(X|No) = P(No|No)*P(Divorced|No)*P(Low|No) = 4/7 * 1/7 * 3/7 > P(X|Yes)

   predict class: No

### Model Evaluation

a) Write a function to generate the confusion matrix for a list of actual classes and a list of predicted classes

In [2]:
import numpy as np

actual_class = ["Yes", "No", "No", "Yes", "No", "No", "Yes", "No", "No", "No"]
predicted_class = ["Yes", "No", "Yes", "No", "No", "No", "Yes", "Yes", "Yes", "No"]

def confusion_matrix(actual, predicted):
    TP, FN, FP, TN = 0,0,0,0
    cm = []
    for i in range(len(actual)):
        if actual[i] =='Yes' and predicted[i] == 'Yes':
            TP += 1
        elif actual[i] == 'Yes' and predicted[i] == 'No':
            FN += 1
        elif actual[i] == 'No' and predicted[i] == 'No':
            TN += 1
        elif actual[i] == 'No' and predicted[i] == 'Yes':
            FP += 1
    cm = np.array([[TP, FN],[FP, TN]])

    return cm

print(confusion_matrix(actual_class, predicted_class))

[[2 1]
 [3 4]]


b) Assume you have the following Cost Matrix:

|            | predicted = Y | predicted = N |
|------------|---------------|---------------|
| actual = Y |       -1      |       5       |
| actual = N |        10     |       0       |

What is the cost of the above classification?

-2 + 5 + 30 + 0 = 33

c) Write a function that takes in the actual values, the predictions, and a cost matrix and outputs a cost. Test it on the above example.

In [3]:
def cost(actual, pred, cost_matrix):
    cm = confusion_matrix(actual, pred)
    print(cm)
    cost = 0
    for i in range(len(cm)):
        for j in range(len(cm[0])):
            cost  += cm[i][j] * cost_matrix[i][j]
    return cost

cost_matrix = np.array([[-1, 5], [10, 0]])

print(cost_matrix)
print(cost(actual_class, predicted_class, cost_matrix))

[[-1  5]
 [10  0]]
[[2 1]
 [3 4]]
33


d) What is the difference between a testing set and a validation set?

The testing set is used to evaluate the final performance of the model after it is fully trained and the hyperparameters are fixed.
The validation set is used during the training process to tune the hyperparameters of the model.

e) What are some things you can do to handle the case where you have a highly imbalanced dataset (i.e. there are way more of one class than another). Describe both how you can provide better visibility into the failures of the model and how you can set your model training up for success.

We can use matrics like confusion matrix to provide better visibility into the failures of the model. We should perform some hyperparameter tuning and try out different models in order to set our model training up for success. 